### ISSUE TITLE
"[…] request that this server could not understand."

### ISSUE THREAD

**Issue by olivierkaisin** [mattcg/socks5-https-client#1]
Hello,

I spotted an issue that probably worths investigation. 

While doing a call to fetch the contents of ``https://check.torproject.org``

I get the following: 

```html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>400 Bad Request</title>
</head><body>
<h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br />
</p>
<hr>
<address>Apache Server at check.torproject.org Port 443</address>
</body></html>
```

To get this, I execute a ``.get()`` with the following parameters:

```javascript
var parameters = { 
  path: '/',
  port: 443,
  protocol: 'https:',
  hostname: 'check.torproject.org',
  socksPort: 9150 };
```

I'll try to help as soon as I have time.

Thanks in advance!

Olivier

**Comment by mattcg** [comment]
This no longer occurs as of Node v0.12.0.
