### ISSUE TITLE
How configure client for resolve the destination hostname on proxy server. 

### ISSUE THREAD

**Issue by jershell** [mattcg/socks5-https-client#14]
Does it exist the option "localDNS: true | false" ?
true - will resolve on local
false - will resolve on remote

**Comment by mattcg** [comment]
The destination hostname will always be resolved by the proxy server. The only DNS resolution that this client does is when it resolves the hostname of the SOCKS server itself (but only if it's a hostname, obviously not if it's an IP address). The client sends the hostname part of the URL you want to request to the SOCKS server, which then has to resolve it.

This makes this client ideal for working with Tor, as it won't leak hostnames.
