### ISSUE TITLE
Sock5 Error

### ISSUE THREAD

**Issue by Vincvn** [mattcg/socks5-https-client#15]
} else if (!authMethods.includes(data[1])) {
		                        ^

TypeError: authMethods.includes is not a function
Thanks

**Comment by mattcg** [comment]
What version of node are you running? [Array.prototype.includes](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/includes) is part of ES6 and is only present in newer versions of node.

**Comment by Vincvn** [comment]
Hi my nodejs version is: v.4.2.6

**Comment by mattcg** [comment]
You're two versions behind the current stable version. Could you upgrade to that?

**Comment by Vincvn** [comment]
I upgraded to lastest LTS and its running normal. Thank you for help
Sorry my english bad

**Comment by mattcg** [comment]
Your English is good! And thank you for using this client.
