### ISSUE TITLE
crash when connection error

### ISSUE THREAD

**Issue by zh99998** [mattcg/socks5-https-client#3]
i have a socks5 server, and

``` coffeescript
request
          url: 'https://www.google.com/',
          agent: new Socks5ClientHttpsAgent
            socksPort: 8080
        , (err, res)->
            if err
              console.log err
```

and then, if meet a network error, tcp connection reset, then i can't get callback err, and as instead it throws an "Error: socket hang up" and i can't catch it anywhere. then crash.

**Comment by AVVS** [comment]
I have a different error - it crashes and gives some random error about cant read error of null.
This issue is happening with 1.x.x branch, but doesnt exit in 0.x.x

**Comment by mattcg** [comment]
@AVVS will you paste in the full error output please?

**Comment by AVVS** [comment]
weird enough the error seems to be gone now that I'm trying to reproduce it to get the trace again. I'll keep an eye on it and post it here if this happens again
