### ISSUE TITLE
Error: socket hang up with 15.7.0 or newer

### ISSUE THREAD

**Issue by aicanfly** [mattcg/socks5-https-client#31]
after this "FIX' I got same problem with socket hang up: https://github.com/nodejs/node/pull/36863/commits/bee7a72930548f010319f29f50f179a0c1da9c54

using https://github.com/mattcg/socks5-https-client combined with request library with node v15.7.0 or newer gives me "Error: socket hang up", with 15.6.0 everything is fine.

https://github.com/nodejs/node/issues/37510

**Comment by andresespinosapc** [comment]
I have the same problem with node v14.17.0, with 14.16.1 it works fine

**Comment by aicanfly** [comment]
> I have the same problem with node v14.17.0, with 14.16.1 it works fine

did you fix it somehow?

**Comment by andresespinosapc** [comment]
Nope :(

**Comment by aicanfly** [comment]
> Nope :(

I created other thread: https://github.com/nodejs/node/issues/37510#issuecomment-850590851
we need to wait till @mattcg fix it

**Comment by aicanfly** [comment]
any news @andresespinosapc ? did you try to fix it by yourself?
