### ISSUE TITLE
Agent does not set socket.authorized, fails "request" module's strictSSL check

### ISSUE THREAD

**Issue by chrisegner** [mattcg/socks5-https-client#8]
When using the Agent through the request package, strictSSL == true causes request to check response.socket.authorized.  The Agent does not set this, and so strictSSL causes all connections to fail with an "SSL Error: undefined" (thrown by request).  Turning off strictSSL checking causes rejectUnauthorized to be set to false, thereby disabling certificate validation, which is pretty rough.

I'm not a security expert, but would it be appropriate to set the response's socket.authorized to true, as is the case for tls.TLSSocket instances.

node: v0.12.7
request: 2.58.0
socks-https-client: 1.1.0

**Comment by mattcg** [comment]
Thanks for reporting, and especially for diagnosing the issue!

**Comment by chrisegner** [comment]
The quick fix is much appreciated!
